config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'pins/search', to: 'pins#search', as: 'pins_search'

  resources :pins do
    resources :comments
  end

  resources :users do
    resources :pinlist
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pin
  belongs_to :user

  validates :body, presence: true
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
    has_many :comments

    #many to many association
    has_and_belongs_to_many :users


    validates :title, presence: true
    validates :tag, length: { maximum: 30 }

    def self.most_recent()
        all.order(created_at: :desc).limit(6)
    end

    def self.search(search_term)
        wildcard_filter = "%#{search_term}%"
        where('title LIKE ?', wildcard_filter).or(where('tag LIKE ?', wildcard_filter))
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :pins

    #refer to it as pinlist, but is an Pin model
    has_and_belongs_to_many :pinlist, class_name: 'Pin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        user = User.find(session[:user_id])
        comment = Comment.new comment_params
        pin = Pin.find(params[:pin_id])
        comment.pin = pin
        comment.user = user
        comment.save

        redirect_to pin_path(pin)
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @pins = Pin.most_recent
    end
end

app/controllers/pinlist_controller.rb
class PinlistController < ApplicationController
    def create
        user = User.find(params[:user_id])
        pin = Pin.find(params[:pin_id])

        user.pinlist << pin # will automatically save!
        
        redirect_to pin_path(pin)
    end

    def index
        user = User.find(params[:user_id])
        @pinlist = user.pinlist
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    def index
        @pins = Pin.all
    end

    def search
        @search_term = params[:q]
        logger.info("Search completed using #{@search_term}.")
        @pins = Pin.search(@search_term)
    end

    def new
        @pin = Pin.new
    end

    def create
        user = User.find(session[:user_id])
        @pin = Pin.new(pins_resource_params)
        @pin.user = user

        if(@pin.save)
            redirect_to pins_path
        else 
            render 'new'  
        end
    end

    def show
        @pin = Pin.find(params[:id])
        @comment = Comment.new
        @display_add_comment = session[:user_id].present?

        if(session[:user_id].present?)
            @user = User.find(session[:user_id])
            @disable_add_pinlist = @user.pinlist.exists?(@pin.id)
        # else
        #     @user = nil
        end
    end

    def edit
        id = params[:id]
        @pin = Pin.find(id)
    end

    def update
        @pin = Pin.find(params[:id])
        if(@pin.update(pins_resource_params))
            redirect_to pins_path
        else
            render 'edit'
        end
    end

    private 
    def pins_resource_params
        params.require(:pin).permit(:title, :image_url, :tag)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.find_or_create_by(user_params)
        session[:user_id] = user.id
        redirect_to pins_path
    end

    private
    
    def user_params
        params.require(:user).permit(:email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
    def isLoggedIn()   
      if(session[:user_id].present?)
        true
      else
        false
      end
    end

    def currentUser()
      if(session[:user_id].present?)
        user = session[:user_id]
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pinlist_helper.rb
module PinlistHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_pin_card.html.erb
<div class="card" style="width: 16rem;">
  <%= link_to(pin_path(pin)) do %>
    <% if(card_img.nil?) %>
      <img class="card-img-top" src="https://images.unsplash.com/photo-1604725333736-1f962a6218d0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmVhdXRpZnVsJTIwc3Vuc2V0fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="card image">
    <% else %>
      <%= image_tag(card_img, class: "card-img-top") %>
    <% end %>
  <% end %>

  <div class="card-body">
    <h5 class="card-title"><%= card_title %></h5>
    <p class="card-text">Created by: <%= card_author %></p>
    <p class="card-text">Tags: <%= card_tags %></p>
  </div>
</div>

app/views/home/index.html.erb
<main>
  <div class="container my-5">
    <%= form_tag(pins_search_path, method: 'GET') do %>
      <div class="form-group">
        <label for="search" class="" for="q">Looking for something particular?</label>
        <div class="d-flex flex-row">
          <%= text_field_tag('q', nil, class: 'form-control', id: "search", placeholder: 'e.g. sunset') %>
          <%= button_tag('Search', class: 'btn btn-primary px-5') %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="container my-5">
    <% if(@pins.any?) %>
      <h2>Latest pins</h2>
      <ul class="d-flex flex-wrap flex-row justify-content-start" style="padding-left: 0;">  
        <% @pins.each do |pin| %>
          <li class="list-group-item border-0 ">
            <%= render(partial: 'pin_card', locals: { card_title: pin.title, card_img: pin.image_url, card_tags: pin.tag, card_author: pin.user.email, pin: pin }) %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex justify-content-center">
        <%= link_to('View all pins', pins_path, class: "btn btn-primary px-5") %>
      </div>
    <% else %>
      <h3>No pins found! </h3>
    <% end %>
  </div>

  

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
   
  <% if(isLoggedIn()) %>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary d-flex justify-content-between">
      <div class="mr-auto p-2">
        <%= link_to('Pinterest', root_path, class: "navbar-brand") %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse p-2 justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/about">About<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <%= link_to('Pin List', user_pinlist_index_path(currentUser()), class: "nav-link") %>
          </li>
        </ul>
      </div>
    </nav>
  <% else %>  
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary d-flex justify-content-between">
      <div class="mr-auto p-2">
        <%= link_to('Pinterest', root_path, class: "navbar-brand") %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse p-2 justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/about">About<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <%= link_to('Login/Sign up', new_user_path(), class: "nav-link") %>
          </li>
        </ul>
      </div>
    </nav>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/pinlist/index.html.erb
<main>
  <div class="container my-5">
    <div class="d-flex justify-content-center">
      <h1> My Personal Pinlist</h1>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to(new_pin_path(), class: 'btn btn-primary px-5') do %>Create a new Pin<% end %>
    </div>
    <hr>
    
    <% if(@pinlist.any?) %>
      <ul class="d-flex flex-wrap flex-row justify-content-start" style="padding-left: 0;">  
        <% @pinlist.each do |pin| %>
          <li class="list-group-item border-0 ">
            <%= render(partial: 'pin_card', locals: { card_title: pin.title, card_img: pin.image_url, card_tags: pin.tag, card_author: pin.user.email, pin: pin }) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <h3>No pins in your personal pinlist were found! </h3>
    <% end %>
    

  </div>
</main>

app/views/pins/_form.html.erb
<% if(pin.errors.any?) %>   
    <div class="text-danger">
        <%= safe_join(pin.errors.full_messages, raw("<br />")) %>
    </div>
<% end %>  
<br>
<%= form_for(pin) do |form| %>
  <div class="form-group">
    <%= form.label(:title) %>
    <%= form.text_field(:title, class: 'form-control', placeholder: "E.g. Ride a camel") %>
  </div>

  <div class="form-group">
    <%= form.label(:image_url) %>
    <%= form.text_field(:image_url, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= form.label(:tag) %>
    <%= form.text_field(:tag, class: 'form-control') %>
  </div>

  <div class="prompt">
    <%= form.submit(class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<main>
  <div class="container my-5">
    <h1>Edit Pin</h1>
    
    <%= render(partial: 'form', locals: { pin: @pin }) %>
  </div>
</main>

app/views/pins/index.html.erb
<main>
  <div class="container my-5">
    <div class="d-flex justify-content-center">
      <h1>All Pins</h1>
    </div>
    <% if(isLoggedIn()) %>
      <div class="d-flex justify-content-center">
        <%= link_to(new_pin_path(), class: 'btn btn-primary') do %>Create a new Pin<% end %>
      </div>
    <% end %>
    <hr>

    <% if(@pins.any?) %>
      <ul class="d-flex flex-wrap flex-row justify-content-start" style="padding-left: 0;">  
        <% @pins.each do |pin| %>
          <li class="list-group-item border-0 ">
            <%= render(partial: 'pin_card', locals: { card_title: pin.title, card_img: pin.image_url, card_tags: pin.tag, card_author: pin.user.email, pin: pin }) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <h3>No pins found!</h3>
    <% end %>
    

  </div>
</main>

app/views/pins/new.html.erb
<main>
  <div class="container my-5">
    <h1>Create a new Pin</h1>

    <%= render(partial: 'form', locals: { pin: @pin }) %>
  </div>
</main>

app/views/pins/search.html.erb
<main>
  <div class="container my-5">
    <h1>Results for "<%= @search_term %>"</h1>
  </div>
  <div class="container my-5">
    <% if(@pins.any?) %>
      <ul class="d-flex flex-wrap flex-row justify-content-start" style="padding-left: 0;">  
        <% @pins.each do |pin| %>
          <li class="list-group-item border-0 ">
            <%= render(partial: 'pin_card', locals: { card_title: pin.title, card_img: pin.image_url, card_tags: pin.tag, card_author: pin.user.email, pin: pin }) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <h3>No pins found matching this search term!</h3>
    <% end %>
  </div>
</main>

app/views/pins/show.html.erb
<main>
  <div class="container my-5 hr d-flex flex-row">
    <div class="w-50">
      <% if(@pin.image_url.nil?) %>
        <img class="img-thumbnail w-75" src="https://images.unsplash.com/photo-1604725333736-1f962a6218d0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmVhdXRpZnVsJTIwc3Vuc2V0fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="card image">
      <% else %>
        <%= image_tag(@pin.image_url, class: "img-thumbnail w-75") %>
      <% end %>
    </div>
    <div>
      <h1><%= @pin.title %></h1>
      <h6>Created by <%= @pin.user.email %> on <%= @pin.created_at.strftime("%d %b '%y") %></h6>
      <hr>
      <h4>Tags: <%= @pin.tag %> </h4>
  
      <% if(isLoggedIn()) %>
        <%= link_to(edit_pin_path(@pin), class: 'btn btn-primary') do %>Edit<% end %>
        <%= form_tag(user_pinlist_index_path(@user)) do %>
          <%= hidden_field_tag('pin_id', @pin.id) %>
          <%= button_tag(class: 'btn btn-primary', type: 'submit', disabled: @disable_add_pinlist) do %>
            Add to personal pin list
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container my-5 hr">
    <h3>Comments: </h3>
    <br>
      <% if(@display_add_comment) %>
        <%= form_for([@pin, @comment]) do |form| %>
          <div class="form-group">
            <%= form.label(:body, 'Add a comment') %>
            <%= form.text_area(:body, class: 'form-control') %>
          </div>
          <%= form.submit('Post', class: 'btn btn-primary') %>
        <% end %>
      <% end %>
    <br>
    <ul class="list-group">
      <% @pin.comments.each do |comment| %>
        <li class="list-group-item flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= comment.user.email %> </h5>            
            <small><%= comment.created_at%></small>
          </div>
          <div>
            <p class="mb-1"><%= comment.body %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</main>

app/views/users/new.html.erb
<main>
  <div class="container my-5">
    <h1>Sign up / Log in</h1>
    <br>
    <%= form_for(@user) do |form| %>
      <div class="form-group">
        <%= form.label(:email) %>
        <%= form.text_field(:email, class: 'form-control', placeholder: 'me@epfl.ch') %>
      </div>
      <div class="prompt">
        <%= form.submit('Log in', class: 'btn btn-primary') %>
      </div>
    <% end %>
  </div>
</main>